batch_size: 8
image_size: [384,384]
test_size: [384,384]
sample_num: 1
DAC_sampling: False
model_configs:
  backbone_name: "convnext_base"
  backbone_configs:
    stages_to_freeze: 0
    return_token: True
    return_chunk: False
  components_name: "CCR"
  components_configs:
    in_channels: 1024
    num_classes: 701
    block: 2
    M: 32
    return_f: 0.3
  optimizer: "sgd"
  loss_config:
    margin: 0.3
    hard_factor: 0.0
    which_contrast_loss: "triplet"
    add_KLloss: True
  lr: 0.01
  lr_sched: "multistep"
  lr_sched_config:
    milestones: [ 80, 120 ]
    gamma: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  warmpup_steps: 500

max_epochs: 200
