batch_size: 24
image_size: [224,224]
test_size: [280,280]
sample_num: 1
DAC_sampling: False
model_configs:
  backbone_name: "dinov2_vitb14"
  backbone_configs:
    layers_to_freeze: 12
    layers_to_crop: []
    norm_layer: True
    return_token: True
    return_token_list: False
    adapter: True
  components_name: "QDFL"
  components_configs:
    in_channels: 768
    num_classes: 701  #do not forget to change when the dataset is changed
    num_supervisor: 2
    query_configs:
      num_queries: 8
    return_f: True
    cls_token: True
  optimizer: "sgd"
  grad_optimizer_name: False
  loss_config:
    margin: 0.4
    hard_factor: 0.0
    which_contrast_loss: "multisim"
    add_KLloss: True
    add_MMDloss: False
    add_MSEloss: False
    kernel_mul: 3
    kernel_num: 5
  lr: 0.03
  lr_sched: "cosine"
  lr_sched_config:
    T_max: 160
  weight_decay: 0.0005
  momentum: 0.9
  warmpup_steps: 175

max_epochs: 160
